/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Arena */

#ifndef _Included_org_example_Arena
#define _Included_org_example_Arena
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Arena
 * Method:    initByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_example_Arena_initByteBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
