/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Native */

#ifndef _Included_org_example_Native
#define _Included_org_example_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Native
 * Method:    curl_easy_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_curl_1easy_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Native
 * Method:    curl_easy_setopt_CURLOPT_URL
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_curl_1easy_1setopt_1CURLOPT_1URL
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_example_Native
 * Method:    curl_easy_setopt_CURLOPT_FOLLOWLOCATION
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_curl_1easy_1setopt_1CURLOPT_1FOLLOWLOCATION
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_example_Native
 * Method:    curl_easy_cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_Native_curl_1easy_1cleanup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_Native
 * Method:    curl_easy_perform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_curl_1easy_1perform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_Native
 * Method:    curl_easy_setopt_CURLOPT_WRITEDATA
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_curl_1easy_1setopt_1CURLOPT_1WRITEDATA
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_Native
 * Method:    fopen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native_fopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_Native
 * Method:    fclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_Native_fclose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
