/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Curl3 */

#ifndef _Included_org_example_Curl3
#define _Included_org_example_Curl3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Curl3
 * Method:    perform
 * Signature: (Lorg/example/http/Request;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Curl3_perform
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
