/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    curlInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_curlInit
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Main
 * Method:    foobar
 * Signature: (Ljava/io/OutputStream;)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_foobar
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_example_Main
 * Method:    test1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_test1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
