package org.example;

public class H {

    public final static int CURLOPT_ABSTRACT_UNIX_SOCKET;
    public final static int CURLOPT_ACCEPTTIMEOUT_MS;
    public final static int CURLOPT_ACCEPT_ENCODING;
    public final static int CURLOPT_ADDRESS_SCOPE;
    public final static int CURLOPT_ALTSVC;
    public final static int CURLOPT_ALTSVC_CTRL;
    public final static int CURLOPT_APPEND;
    public final static int CURLOPT_AUTOREFERER;
    public final static int CURLOPT_AWS_SIGV4;
    public final static int CURLOPT_BUFFERSIZE;
    public final static int CURLOPT_CAINFO;
    public final static int CURLOPT_CAINFO_BLOB;
    public final static int CURLOPT_CAPATH;
    public final static int CURLOPT_CA_CACHE_TIMEOUT;
    public final static int CURLOPT_CERTINFO;
    public final static int CURLOPT_CHUNK_BGN_FUNCTION;
    public final static int CURLOPT_CHUNK_DATA;
    public final static int CURLOPT_CHUNK_END_FUNCTION;
    public final static int CURLOPT_CLOSESOCKETDATA;
    public final static int CURLOPT_CLOSESOCKETFUNCTION;
    public final static int CURLOPT_CONNECTTIMEOUT;
    public final static int CURLOPT_CONNECTTIMEOUT_MS;
    public final static int CURLOPT_CONNECT_ONLY;
    public final static int CURLOPT_CONNECT_TO;
    public final static int CURLOPT_CONV_FROM_NETWORK_FUNCTION;
    public final static int CURLOPT_CONV_FROM_UTF8_FUNCTION;
    public final static int CURLOPT_CONV_TO_NETWORK_FUNCTION;
    public final static int CURLOPT_COOKIE;
    public final static int CURLOPT_COOKIEFILE;
    public final static int CURLOPT_COOKIEJAR;
    public final static int CURLOPT_COOKIELIST;
    public final static int CURLOPT_COOKIESESSION;
    public final static int CURLOPT_COPYPOSTFIELDS;
    public final static int CURLOPT_CRLF;
    public final static int CURLOPT_CRLFILE;
    public final static int CURLOPT_CURLU;
    public final static int CURLOPT_CUSTOMREQUEST;
    public final static int CURLOPT_DEBUGDATA;
    public final static int CURLOPT_DEBUGFUNCTION;
    public final static int CURLOPT_DEFAULT_PROTOCOL;
    public final static int CURLOPT_DIRLISTONLY;
    public final static int CURLOPT_DISALLOW_USERNAME_IN_URL;
    public final static int CURLOPT_DNS_CACHE_TIMEOUT;
    public final static int CURLOPT_DNS_INTERFACE;
    public final static int CURLOPT_DNS_LOCAL_IP4;
    public final static int CURLOPT_DNS_LOCAL_IP6;
    public final static int CURLOPT_DNS_SERVERS;
    public final static int CURLOPT_DNS_SHUFFLE_ADDRESSES;
    public final static int CURLOPT_DNS_USE_GLOBAL_CACHE;
    public final static int CURLOPT_DOH_SSL_VERIFYHOST;
    public final static int CURLOPT_DOH_SSL_VERIFYPEER;
    public final static int CURLOPT_DOH_SSL_VERIFYSTATUS;
    public final static int CURLOPT_DOH_URL;
    public final static int CURLOPT_ECH;
    public final static int CURLOPT_EGDSOCKET;
    public final static int CURLOPT_ERRORBUFFER;
    public final static int CURLOPT_EXPECT_100_TIMEOUT_MS;
    public final static int CURLOPT_FAILONERROR;
    public final static int CURLOPT_FILETIME;
    public final static int CURLOPT_FNMATCH_DATA;
    public final static int CURLOPT_FNMATCH_FUNCTION;
    public final static int CURLOPT_FOLLOWLOCATION;
    public final static int CURLOPT_FORBID_REUSE;
    public final static int CURLOPT_FRESH_CONNECT;
    public final static int CURLOPT_FTPPORT;
    public final static int CURLOPT_FTPSSLAUTH;
    public final static int CURLOPT_FTP_ACCOUNT;
    public final static int CURLOPT_FTP_ALTERNATIVE_TO_USER;
    public final static int CURLOPT_FTP_CREATE_MISSING_DIRS;
    public final static int CURLOPT_FTP_FILEMETHOD;
    public final static int CURLOPT_FTP_SKIP_PASV_IP;
    public final static int CURLOPT_FTP_SSL_CCC;
    public final static int CURLOPT_FTP_USE_EPRT;
    public final static int CURLOPT_FTP_USE_EPSV;
    public final static int CURLOPT_FTP_USE_PRET;
    public final static int CURLOPT_GSSAPI_DELEGATION;
    public final static int CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS;
    public final static int CURLOPT_HAPROXYPROTOCOL;
    public final static int CURLOPT_HAPROXY_CLIENT_IP;
    public final static int CURLOPT_HEADER;
    public final static int CURLOPT_HEADERDATA;
    public final static int CURLOPT_HEADERFUNCTION;
    public final static int CURLOPT_HEADEROPT;
    public final static int CURLOPT_HSTS;
    public final static int CURLOPT_HSTSREADDATA;
    public final static int CURLOPT_HSTSREADFUNCTION;
    public final static int CURLOPT_HSTSWRITEDATA;
    public final static int CURLOPT_HSTSWRITEFUNCTION;
    public final static int CURLOPT_HSTS_CTRL;
    public final static int CURLOPT_HTTP09_ALLOWED;
    public final static int CURLOPT_HTTP200ALIASES;
    public final static int CURLOPT_HTTPAUTH;
    public final static int CURLOPT_HTTPGET;
    public final static int CURLOPT_HTTPHEADER;
    public final static int CURLOPT_HTTPPOST;
    public final static int CURLOPT_HTTPPROXYTUNNEL;
    public final static int CURLOPT_HTTPSIG_ALGORITHM;
    public final static int CURLOPT_HTTPSIG_HEADERS;
    public final static int CURLOPT_HTTPSIG_KEY;
    public final static int CURLOPT_HTTPSIG_KEYID;
    public final static int CURLOPT_HTTP_CONTENT_DECODING;
    public final static int CURLOPT_HTTP_TRANSFER_DECODING;
    public final static int CURLOPT_HTTP_VERSION;
    public final static int CURLOPT_IGNORE_CONTENT_LENGTH;
    public final static int CURLOPT_INFILESIZE;
    public final static int CURLOPT_INFILESIZE_LARGE;
    public final static int CURLOPT_INTERFACE;
    public final static int CURLOPT_INTERLEAVEDATA;
    public final static int CURLOPT_INTERLEAVEFUNCTION;
    public final static int CURLOPT_IOCTLDATA;
    public final static int CURLOPT_IOCTLFUNCTION;
    public final static int CURLOPT_IPRESOLVE;
    public final static int CURLOPT_ISSUERCERT;
    public final static int CURLOPT_ISSUERCERT_BLOB;
    public final static int CURLOPT_KEEP_SENDING_ON_ERROR;
    public final static int CURLOPT_KEYPASSWD;
    public final static int CURLOPT_KRBLEVEL;
    public final static int CURLOPT_LOCALPORT;
    public final static int CURLOPT_LOCALPORTRANGE;
    public final static int CURLOPT_LOGIN_OPTIONS;
    public final static int CURLOPT_LOW_SPEED_LIMIT;
    public final static int CURLOPT_LOW_SPEED_TIME;
    public final static int CURLOPT_MAIL_AUTH;
    public final static int CURLOPT_MAIL_FROM;
    public final static int CURLOPT_MAIL_RCPT;
    public final static int CURLOPT_MAIL_RCPT_ALLOWFAILS;
    public final static int CURLOPT_MAXAGE_CONN;
    public final static int CURLOPT_MAXCONNECTS;
    public final static int CURLOPT_MAXFILESIZE;
    public final static int CURLOPT_MAXFILESIZE_LARGE;
    public final static int CURLOPT_MAXLIFETIME_CONN;
    public final static int CURLOPT_MAXREDIRS;
    public final static int CURLOPT_MAX_RECV_SPEED_LARGE;
    public final static int CURLOPT_MAX_SEND_SPEED_LARGE;
    public final static int CURLOPT_MIMEPOST;
    public final static int CURLOPT_MIME_OPTIONS;
    public final static int CURLOPT_NETRC;
    public final static int CURLOPT_NETRC_FILE;
    public final static int CURLOPT_NEW_DIRECTORY_PERMS;
    public final static int CURLOPT_NEW_FILE_PERMS;
    public final static int CURLOPT_NOBODY;
    public final static int CURLOPT_NOPROGRESS;
    public final static int CURLOPT_NOPROXY;
    public final static int CURLOPT_NOSIGNAL;
    public final static int CURLOPT_OPENSOCKETDATA;
    public final static int CURLOPT_OPENSOCKETFUNCTION;
    public final static int CURLOPT_PASSWORD;
    public final static int CURLOPT_PATH_AS_IS;
    public final static int CURLOPT_PINNEDPUBLICKEY;
    public final static int CURLOPT_PIPEWAIT;
    public final static int CURLOPT_PORT;
    public final static int CURLOPT_POST;
    public final static int CURLOPT_POSTFIELDS;
    public final static int CURLOPT_POSTFIELDSIZE;
    public final static int CURLOPT_POSTFIELDSIZE_LARGE;
    public final static int CURLOPT_POSTQUOTE;
    public final static int CURLOPT_POSTREDIR;
    public final static int CURLOPT_PREQUOTE;
    public final static int CURLOPT_PREREQDATA;
    public final static int CURLOPT_PREREQFUNCTION;
    public final static int CURLOPT_PRE_PROXY;
    public final static int CURLOPT_PRIVATE;
    public final static int CURLOPT_PROGRESSDATA;
    public final static int CURLOPT_PROGRESSFUNCTION;
    public final static int CURLOPT_PROTOCOLS;
    public final static int CURLOPT_PROTOCOLS_STR;
    public final static int CURLOPT_PROXY;
    public final static int CURLOPT_PROXYAUTH;
    public final static int CURLOPT_PROXYHEADER;
    public final static int CURLOPT_PROXYPASSWORD;
    public final static int CURLOPT_PROXYPORT;
    public final static int CURLOPT_PROXYTYPE;
    public final static int CURLOPT_PROXYUSERNAME;
    public final static int CURLOPT_PROXYUSERPWD;
    public final static int CURLOPT_PROXY_CAINFO;
    public final static int CURLOPT_PROXY_CAINFO_BLOB;
    public final static int CURLOPT_PROXY_CAPATH;
    public final static int CURLOPT_PROXY_CRLFILE;
    public final static int CURLOPT_PROXY_ISSUERCERT;
    public final static int CURLOPT_PROXY_ISSUERCERT_BLOB;
    public final static int CURLOPT_PROXY_KEYPASSWD;
    public final static int CURLOPT_PROXY_PINNEDPUBLICKEY;
    public final static int CURLOPT_PROXY_SERVICE_NAME;
    public final static int CURLOPT_PROXY_SSLCERT;
    public final static int CURLOPT_PROXY_SSLCERTTYPE;
    public final static int CURLOPT_PROXY_SSLCERT_BLOB;
    public final static int CURLOPT_PROXY_SSLKEY;
    public final static int CURLOPT_PROXY_SSLKEYTYPE;
    public final static int CURLOPT_PROXY_SSLKEY_BLOB;
    public final static int CURLOPT_PROXY_SSLVERSION;
    public final static int CURLOPT_PROXY_SSL_CIPHER_LIST;
    public final static int CURLOPT_PROXY_SSL_OPTIONS;
    public final static int CURLOPT_PROXY_SSL_VERIFYHOST;
    public final static int CURLOPT_PROXY_SSL_VERIFYPEER;
    public final static int CURLOPT_PROXY_TLS13_CIPHERS;
    public final static int CURLOPT_PROXY_TLSAUTH_PASSWORD;
    public final static int CURLOPT_PROXY_TLSAUTH_TYPE;
    public final static int CURLOPT_PROXY_TLSAUTH_USERNAME;
    public final static int CURLOPT_PROXY_TRANSFER_MODE;
    public final static int CURLOPT_PUT;
    public final static int CURLOPT_QUICK_EXIT;
    public final static int CURLOPT_QUOTE;
    public final static int CURLOPT_RANDOM_FILE;
    public final static int CURLOPT_RANGE;
    public final static int CURLOPT_READDATA;
    public final static int CURLOPT_READFUNCTION;
    public final static int CURLOPT_REDIR_PROTOCOLS;
    public final static int CURLOPT_REDIR_PROTOCOLS_STR;
    public final static int CURLOPT_REFERER;
    public final static int CURLOPT_REQUEST_TARGET;
    public final static int CURLOPT_RESOLVE;
    public final static int CURLOPT_RESOLVER_START_DATA;
    public final static int CURLOPT_RESOLVER_START_FUNCTION;
    public final static int CURLOPT_RESUME_FROM;
    public final static int CURLOPT_RESUME_FROM_LARGE;
    public final static int CURLOPT_RTSP_CLIENT_CSEQ;
    public final static int CURLOPT_RTSP_REQUEST;
    public final static int CURLOPT_RTSP_SERVER_CSEQ;
    public final static int CURLOPT_RTSP_SESSION_ID;
    public final static int CURLOPT_RTSP_STREAM_URI;
    public final static int CURLOPT_RTSP_TRANSPORT;
    public final static int CURLOPT_SASL_AUTHZID;
    public final static int CURLOPT_SASL_IR;
    public final static int CURLOPT_SEEKDATA;
    public final static int CURLOPT_SEEKFUNCTION;
    public final static int CURLOPT_SERVER_RESPONSE_TIMEOUT;
    public final static int CURLOPT_SERVER_RESPONSE_TIMEOUT_MS;
    public final static int CURLOPT_SERVICE_NAME;
    public final static int CURLOPT_SHARE;
    public final static int CURLOPT_SOCKOPTDATA;
    public final static int CURLOPT_SOCKOPTFUNCTION;
    public final static int CURLOPT_SOCKS5_AUTH;
    public final static int CURLOPT_SOCKS5_GSSAPI_NEC;
    public final static int CURLOPT_SOCKS5_GSSAPI_SERVICE;
    public final static int CURLOPT_SSH_AUTH_TYPES;
    public final static int CURLOPT_SSH_COMPRESSION;
    public final static int CURLOPT_SSH_HOSTKEYDATA;
    public final static int CURLOPT_SSH_HOSTKEYFUNCTION;
    public final static int CURLOPT_SSH_HOST_PUBLIC_KEY_MD5;
    public final static int CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256;
    public final static int CURLOPT_SSH_KEYDATA;
    public final static int CURLOPT_SSH_KEYFUNCTION;
    public final static int CURLOPT_SSH_KNOWNHOSTS;
    public final static int CURLOPT_SSH_PRIVATE_KEYFILE;
    public final static int CURLOPT_SSH_PUBLIC_KEYFILE;
    public final static int CURLOPT_SSLCERT;
    public final static int CURLOPT_SSLCERTTYPE;
    public final static int CURLOPT_SSLCERT_BLOB;
    public final static int CURLOPT_SSLENGINE;
    public final static int CURLOPT_SSLENGINE_DEFAULT;
    public final static int CURLOPT_SSLKEY;
    public final static int CURLOPT_SSLKEYTYPE;
    public final static int CURLOPT_SSLKEY_BLOB;
    public final static int CURLOPT_SSLVERSION;
    public final static int CURLOPT_SSL_CIPHER_LIST;
    public final static int CURLOPT_SSL_CTX_DATA;
    public final static int CURLOPT_SSL_CTX_FUNCTION;
    public final static int CURLOPT_SSL_EC_CURVES;
    public final static int CURLOPT_SSL_ENABLE_ALPN;
    public final static int CURLOPT_SSL_ENABLE_NPN;
    public final static int CURLOPT_SSL_FALSESTART;
    public final static int CURLOPT_SSL_OPTIONS;
    public final static int CURLOPT_SSL_SESSIONID_CACHE;
    public final static int CURLOPT_SSL_SIGNATURE_ALGORITHMS;
    public final static int CURLOPT_SSL_VERIFYHOST;
    public final static int CURLOPT_SSL_VERIFYPEER;
    public final static int CURLOPT_SSL_VERIFYSTATUS;
    public final static int CURLOPT_STDERR;
    public final static int CURLOPT_STREAM_DEPENDS;
    public final static int CURLOPT_STREAM_DEPENDS_E;
    public final static int CURLOPT_STREAM_WEIGHT;
    public final static int CURLOPT_SUPPRESS_CONNECT_HEADERS;
    public final static int CURLOPT_TCP_FASTOPEN;
    public final static int CURLOPT_TCP_KEEPALIVE;
    public final static int CURLOPT_TCP_KEEPCNT;
    public final static int CURLOPT_TCP_KEEPIDLE;
    public final static int CURLOPT_TCP_KEEPINTVL;
    public final static int CURLOPT_TCP_NODELAY;
    public final static int CURLOPT_TELNETOPTIONS;
    public final static int CURLOPT_TFTP_BLKSIZE;
    public final static int CURLOPT_TFTP_NO_OPTIONS;
    public final static int CURLOPT_TIMECONDITION;
    public final static int CURLOPT_TIMEOUT;
    public final static int CURLOPT_TIMEOUT_MS;
    public final static int CURLOPT_TIMEVALUE;
    public final static int CURLOPT_TIMEVALUE_LARGE;
    public final static int CURLOPT_TLS13_CIPHERS;
    public final static int CURLOPT_TLSAUTH_PASSWORD;
    public final static int CURLOPT_TLSAUTH_TYPE;
    public final static int CURLOPT_TLSAUTH_USERNAME;
    public final static int CURLOPT_TRAILERDATA;
    public final static int CURLOPT_TRAILERFUNCTION;
    public final static int CURLOPT_TRANSFERTEXT;
    public final static int CURLOPT_TRANSFER_ENCODING;
    public final static int CURLOPT_UNIX_SOCKET_PATH;
    public final static int CURLOPT_UNRESTRICTED_AUTH;
    public final static int CURLOPT_UPKEEP_INTERVAL_MS;
    public final static int CURLOPT_UPLOAD;
    public final static int CURLOPT_UPLOAD_BUFFERSIZE;
    public final static int CURLOPT_UPLOAD_FLAGS;
    public final static int CURLOPT_URL;
    public final static int CURLOPT_USERAGENT;
    public final static int CURLOPT_USERNAME;
    public final static int CURLOPT_USERPWD;
    public final static int CURLOPT_USE_SSL;
    public final static int CURLOPT_VERBOSE;
    public final static int CURLOPT_WILDCARDMATCH;
    public final static int CURLOPT_WRITEDATA;
    public final static int CURLOPT_WRITEFUNCTION;
    public final static int CURLOPT_WS_OPTIONS;
    public final static int CURLOPT_XFERINFODATA;
    public final static int CURLOPT_XFERINFOFUNCTION;
    public final static int CURLOPT_XOAUTH2_BEARER;

    static {

        // TODO size;
        final Arena arena = Arena.of(32000);
        Native.read_curl_constants(arena.ptr());

        arena.orderJNI();
        arena.rewind();

        CURLOPT_ABSTRACT_UNIX_SOCKET       = arena.getInt();
        CURLOPT_ACCEPTTIMEOUT_MS           = arena.getInt();
        CURLOPT_ACCEPT_ENCODING            = arena.getInt();
        CURLOPT_ADDRESS_SCOPE              = arena.getInt();
        CURLOPT_ALTSVC                     = arena.getInt();
        CURLOPT_ALTSVC_CTRL                = arena.getInt();
        CURLOPT_APPEND                     = arena.getInt();
        CURLOPT_AUTOREFERER                = arena.getInt();
        CURLOPT_AWS_SIGV4                  = arena.getInt();
        CURLOPT_BUFFERSIZE                 = arena.getInt();
        CURLOPT_CAINFO                     = arena.getInt();
        CURLOPT_CAINFO_BLOB                = arena.getInt();
        CURLOPT_CAPATH                     = arena.getInt();
        CURLOPT_CA_CACHE_TIMEOUT           = arena.getInt();
        CURLOPT_CERTINFO                   = arena.getInt();
        CURLOPT_CHUNK_BGN_FUNCTION         = arena.getInt();
        CURLOPT_CHUNK_DATA                 = arena.getInt();
        CURLOPT_CHUNK_END_FUNCTION         = arena.getInt();
        CURLOPT_CLOSESOCKETDATA            = arena.getInt();
        CURLOPT_CLOSESOCKETFUNCTION        = arena.getInt();
        CURLOPT_CONNECTTIMEOUT             = arena.getInt();
        CURLOPT_CONNECTTIMEOUT_MS          = arena.getInt();
        CURLOPT_CONNECT_ONLY               = arena.getInt();
        CURLOPT_CONNECT_TO                 = arena.getInt();
        CURLOPT_CONV_FROM_NETWORK_FUNCTION = arena.getInt();
        CURLOPT_CONV_FROM_UTF8_FUNCTION    = arena.getInt();
        CURLOPT_CONV_TO_NETWORK_FUNCTION   = arena.getInt();
        CURLOPT_COOKIE                     = arena.getInt();
        CURLOPT_COOKIEFILE                 = arena.getInt();
        CURLOPT_COOKIEJAR                  = arena.getInt();
        CURLOPT_COOKIELIST                 = arena.getInt();
        CURLOPT_COOKIESESSION              = arena.getInt();
        CURLOPT_COPYPOSTFIELDS             = arena.getInt();
        CURLOPT_CRLF                       = arena.getInt();
        CURLOPT_CRLFILE                    = arena.getInt();
        CURLOPT_CURLU                      = arena.getInt();
        CURLOPT_CUSTOMREQUEST              = arena.getInt();
        CURLOPT_DEBUGDATA                  = arena.getInt();
        CURLOPT_DEBUGFUNCTION              = arena.getInt();
        CURLOPT_DEFAULT_PROTOCOL           = arena.getInt();
        CURLOPT_DIRLISTONLY                = arena.getInt();
        CURLOPT_DISALLOW_USERNAME_IN_URL   = arena.getInt();
        CURLOPT_DNS_CACHE_TIMEOUT          = arena.getInt();
        CURLOPT_DNS_INTERFACE              = arena.getInt();
        CURLOPT_DNS_LOCAL_IP4              = arena.getInt();
        CURLOPT_DNS_LOCAL_IP6              = arena.getInt();
        CURLOPT_DNS_SERVERS                = arena.getInt();
        CURLOPT_DNS_SHUFFLE_ADDRESSES      = arena.getInt();
        CURLOPT_DNS_USE_GLOBAL_CACHE       = arena.getInt();
        CURLOPT_DOH_SSL_VERIFYHOST         = arena.getInt();
        CURLOPT_DOH_SSL_VERIFYPEER         = arena.getInt();
        CURLOPT_DOH_SSL_VERIFYSTATUS       = arena.getInt();
        CURLOPT_DOH_URL                    = arena.getInt();
        CURLOPT_ECH                        = arena.getInt();
        CURLOPT_EGDSOCKET                  = arena.getInt();
        CURLOPT_ERRORBUFFER                = arena.getInt();
        CURLOPT_EXPECT_100_TIMEOUT_MS      = arena.getInt();
        CURLOPT_FAILONERROR                = arena.getInt();
        CURLOPT_FILETIME                   = arena.getInt();
        CURLOPT_FNMATCH_DATA               = arena.getInt();
        CURLOPT_FNMATCH_FUNCTION           = arena.getInt();
        CURLOPT_FOLLOWLOCATION             = arena.getInt();
        CURLOPT_FORBID_REUSE               = arena.getInt();
        CURLOPT_FRESH_CONNECT              = arena.getInt();
        CURLOPT_FTPPORT                    = arena.getInt();
        CURLOPT_FTPSSLAUTH                 = arena.getInt();
        CURLOPT_FTP_ACCOUNT                = arena.getInt();
        CURLOPT_FTP_ALTERNATIVE_TO_USER    = arena.getInt();
        CURLOPT_FTP_CREATE_MISSING_DIRS    = arena.getInt();
        CURLOPT_FTP_FILEMETHOD             = arena.getInt();
        CURLOPT_FTP_SKIP_PASV_IP           = arena.getInt();
        CURLOPT_FTP_SSL_CCC                = arena.getInt();
        CURLOPT_FTP_USE_EPRT               = arena.getInt();
        CURLOPT_FTP_USE_EPSV               = arena.getInt();
        CURLOPT_FTP_USE_PRET               = arena.getInt();
        CURLOPT_GSSAPI_DELEGATION          = arena.getInt();
        CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS  = arena.getInt();
        CURLOPT_HAPROXYPROTOCOL            = arena.getInt();
        CURLOPT_HAPROXY_CLIENT_IP          = arena.getInt();
        CURLOPT_HEADER                     = arena.getInt();
        CURLOPT_HEADERDATA                 = arena.getInt();
        CURLOPT_HEADERFUNCTION             = arena.getInt();
        CURLOPT_HEADEROPT                  = arena.getInt();
        CURLOPT_HSTS                       = arena.getInt();
        CURLOPT_HSTSREADDATA               = arena.getInt();
        CURLOPT_HSTSREADFUNCTION           = arena.getInt();
        CURLOPT_HSTSWRITEDATA              = arena.getInt();
        CURLOPT_HSTSWRITEFUNCTION          = arena.getInt();
        CURLOPT_HSTS_CTRL                  = arena.getInt();
        CURLOPT_HTTP09_ALLOWED             = arena.getInt();
        CURLOPT_HTTP200ALIASES             = arena.getInt();
        CURLOPT_HTTPAUTH                   = arena.getInt();
        CURLOPT_HTTPGET                    = arena.getInt();
        CURLOPT_HTTPHEADER                 = arena.getInt();
        CURLOPT_HTTPPOST                   = arena.getInt();
        CURLOPT_HTTPPROXYTUNNEL            = arena.getInt();
        CURLOPT_HTTPSIG_ALGORITHM          = arena.getInt();
        CURLOPT_HTTPSIG_HEADERS            = arena.getInt();
        CURLOPT_HTTPSIG_KEY                = arena.getInt();
        CURLOPT_HTTPSIG_KEYID              = arena.getInt();
        CURLOPT_HTTP_CONTENT_DECODING      = arena.getInt();
        CURLOPT_HTTP_TRANSFER_DECODING     = arena.getInt();
        CURLOPT_HTTP_VERSION               = arena.getInt();
        CURLOPT_IGNORE_CONTENT_LENGTH      = arena.getInt();
        CURLOPT_INFILESIZE                 = arena.getInt();
        CURLOPT_INFILESIZE_LARGE           = arena.getInt();
        CURLOPT_INTERFACE                  = arena.getInt();
        CURLOPT_INTERLEAVEDATA             = arena.getInt();
        CURLOPT_INTERLEAVEFUNCTION         = arena.getInt();
        CURLOPT_IOCTLDATA                  = arena.getInt();
        CURLOPT_IOCTLFUNCTION              = arena.getInt();
        CURLOPT_IPRESOLVE                  = arena.getInt();
        CURLOPT_ISSUERCERT                 = arena.getInt();
        CURLOPT_ISSUERCERT_BLOB            = arena.getInt();
        CURLOPT_KEEP_SENDING_ON_ERROR      = arena.getInt();
        CURLOPT_KEYPASSWD                  = arena.getInt();
        CURLOPT_KRBLEVEL                   = arena.getInt();
        CURLOPT_LOCALPORT                  = arena.getInt();
        CURLOPT_LOCALPORTRANGE             = arena.getInt();
        CURLOPT_LOGIN_OPTIONS              = arena.getInt();
        CURLOPT_LOW_SPEED_LIMIT            = arena.getInt();
        CURLOPT_LOW_SPEED_TIME             = arena.getInt();
        CURLOPT_MAIL_AUTH                  = arena.getInt();
        CURLOPT_MAIL_FROM                  = arena.getInt();
        CURLOPT_MAIL_RCPT                  = arena.getInt();
        CURLOPT_MAIL_RCPT_ALLOWFAILS       = arena.getInt();
        CURLOPT_MAXAGE_CONN                = arena.getInt();
        CURLOPT_MAXCONNECTS                = arena.getInt();
        CURLOPT_MAXFILESIZE                = arena.getInt();
        CURLOPT_MAXFILESIZE_LARGE          = arena.getInt();
        CURLOPT_MAXLIFETIME_CONN           = arena.getInt();
        CURLOPT_MAXREDIRS                  = arena.getInt();
        CURLOPT_MAX_RECV_SPEED_LARGE       = arena.getInt();
        CURLOPT_MAX_SEND_SPEED_LARGE       = arena.getInt();
        CURLOPT_MIMEPOST                   = arena.getInt();
        CURLOPT_MIME_OPTIONS               = arena.getInt();
        CURLOPT_NETRC                      = arena.getInt();
        CURLOPT_NETRC_FILE                 = arena.getInt();
        CURLOPT_NEW_DIRECTORY_PERMS        = arena.getInt();
        CURLOPT_NEW_FILE_PERMS             = arena.getInt();
        CURLOPT_NOBODY                     = arena.getInt();
        CURLOPT_NOPROGRESS                 = arena.getInt();
        CURLOPT_NOPROXY                    = arena.getInt();
        CURLOPT_NOSIGNAL                   = arena.getInt();
        CURLOPT_OPENSOCKETDATA             = arena.getInt();
        CURLOPT_OPENSOCKETFUNCTION         = arena.getInt();
        CURLOPT_PASSWORD                   = arena.getInt();
        CURLOPT_PATH_AS_IS                 = arena.getInt();
        CURLOPT_PINNEDPUBLICKEY            = arena.getInt();
        CURLOPT_PIPEWAIT                   = arena.getInt();
        CURLOPT_PORT                       = arena.getInt();
        CURLOPT_POST                       = arena.getInt();
        CURLOPT_POSTFIELDS                 = arena.getInt();
        CURLOPT_POSTFIELDSIZE              = arena.getInt();
        CURLOPT_POSTFIELDSIZE_LARGE        = arena.getInt();
        CURLOPT_POSTQUOTE                  = arena.getInt();
        CURLOPT_POSTREDIR                  = arena.getInt();
        CURLOPT_PREQUOTE                   = arena.getInt();
        CURLOPT_PREREQDATA                 = arena.getInt();
        CURLOPT_PREREQFUNCTION             = arena.getInt();
        CURLOPT_PRE_PROXY                  = arena.getInt();
        CURLOPT_PRIVATE                    = arena.getInt();
        CURLOPT_PROGRESSDATA               = arena.getInt();
        CURLOPT_PROGRESSFUNCTION           = arena.getInt();
        CURLOPT_PROTOCOLS                  = arena.getInt();
        CURLOPT_PROTOCOLS_STR              = arena.getInt();
        CURLOPT_PROXY                      = arena.getInt();
        CURLOPT_PROXYAUTH                  = arena.getInt();
        CURLOPT_PROXYHEADER                = arena.getInt();
        CURLOPT_PROXYPASSWORD              = arena.getInt();
        CURLOPT_PROXYPORT                  = arena.getInt();
        CURLOPT_PROXYTYPE                  = arena.getInt();
        CURLOPT_PROXYUSERNAME              = arena.getInt();
        CURLOPT_PROXYUSERPWD               = arena.getInt();
        CURLOPT_PROXY_CAINFO               = arena.getInt();
        CURLOPT_PROXY_CAINFO_BLOB          = arena.getInt();
        CURLOPT_PROXY_CAPATH               = arena.getInt();
        CURLOPT_PROXY_CRLFILE              = arena.getInt();
        CURLOPT_PROXY_ISSUERCERT           = arena.getInt();
        CURLOPT_PROXY_ISSUERCERT_BLOB      = arena.getInt();
        CURLOPT_PROXY_KEYPASSWD            = arena.getInt();
        CURLOPT_PROXY_PINNEDPUBLICKEY      = arena.getInt();
        CURLOPT_PROXY_SERVICE_NAME         = arena.getInt();
        CURLOPT_PROXY_SSLCERT              = arena.getInt();
        CURLOPT_PROXY_SSLCERTTYPE          = arena.getInt();
        CURLOPT_PROXY_SSLCERT_BLOB         = arena.getInt();
        CURLOPT_PROXY_SSLKEY               = arena.getInt();
        CURLOPT_PROXY_SSLKEYTYPE           = arena.getInt();
        CURLOPT_PROXY_SSLKEY_BLOB          = arena.getInt();
        CURLOPT_PROXY_SSLVERSION           = arena.getInt();
        CURLOPT_PROXY_SSL_CIPHER_LIST      = arena.getInt();
        CURLOPT_PROXY_SSL_OPTIONS          = arena.getInt();
        CURLOPT_PROXY_SSL_VERIFYHOST       = arena.getInt();
        CURLOPT_PROXY_SSL_VERIFYPEER       = arena.getInt();
        CURLOPT_PROXY_TLS13_CIPHERS        = arena.getInt();
        CURLOPT_PROXY_TLSAUTH_PASSWORD     = arena.getInt();
        CURLOPT_PROXY_TLSAUTH_TYPE         = arena.getInt();
        CURLOPT_PROXY_TLSAUTH_USERNAME     = arena.getInt();
        CURLOPT_PROXY_TRANSFER_MODE        = arena.getInt();
        CURLOPT_PUT                        = arena.getInt();
        CURLOPT_QUICK_EXIT                 = arena.getInt();
        CURLOPT_QUOTE                      = arena.getInt();
        CURLOPT_RANDOM_FILE                = arena.getInt();
        CURLOPT_RANGE                      = arena.getInt();
        CURLOPT_READDATA                   = arena.getInt();
        CURLOPT_READFUNCTION               = arena.getInt();
        CURLOPT_REDIR_PROTOCOLS            = arena.getInt();
        CURLOPT_REDIR_PROTOCOLS_STR        = arena.getInt();
        CURLOPT_REFERER                    = arena.getInt();
        CURLOPT_REQUEST_TARGET             = arena.getInt();
        CURLOPT_RESOLVE                    = arena.getInt();
        CURLOPT_RESOLVER_START_DATA        = arena.getInt();
        CURLOPT_RESOLVER_START_FUNCTION    = arena.getInt();
        CURLOPT_RESUME_FROM                = arena.getInt();
        CURLOPT_RESUME_FROM_LARGE          = arena.getInt();
        CURLOPT_RTSP_CLIENT_CSEQ           = arena.getInt();
        CURLOPT_RTSP_REQUEST               = arena.getInt();
        CURLOPT_RTSP_SERVER_CSEQ           = arena.getInt();
        CURLOPT_RTSP_SESSION_ID            = arena.getInt();
        CURLOPT_RTSP_STREAM_URI            = arena.getInt();
        CURLOPT_RTSP_TRANSPORT             = arena.getInt();
        CURLOPT_SASL_AUTHZID               = arena.getInt();
        CURLOPT_SASL_IR                    = arena.getInt();
        CURLOPT_SEEKDATA                   = arena.getInt();
        CURLOPT_SEEKFUNCTION               = arena.getInt();
        CURLOPT_SERVER_RESPONSE_TIMEOUT    = arena.getInt();
        CURLOPT_SERVER_RESPONSE_TIMEOUT_MS = arena.getInt();
        CURLOPT_SERVICE_NAME               = arena.getInt();
        CURLOPT_SHARE                      = arena.getInt();
        CURLOPT_SOCKOPTDATA                = arena.getInt();
        CURLOPT_SOCKOPTFUNCTION            = arena.getInt();
        CURLOPT_SOCKS5_AUTH                = arena.getInt();
        CURLOPT_SOCKS5_GSSAPI_NEC          = arena.getInt();
        CURLOPT_SOCKS5_GSSAPI_SERVICE      = arena.getInt();
        CURLOPT_SSH_AUTH_TYPES             = arena.getInt();
        CURLOPT_SSH_COMPRESSION            = arena.getInt();
        CURLOPT_SSH_HOSTKEYDATA            = arena.getInt();
        CURLOPT_SSH_HOSTKEYFUNCTION        = arena.getInt();
        CURLOPT_SSH_HOST_PUBLIC_KEY_MD5    = arena.getInt();
        CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 = arena.getInt();
        CURLOPT_SSH_KEYDATA                = arena.getInt();
        CURLOPT_SSH_KEYFUNCTION            = arena.getInt();
        CURLOPT_SSH_KNOWNHOSTS             = arena.getInt();
        CURLOPT_SSH_PRIVATE_KEYFILE        = arena.getInt();
        CURLOPT_SSH_PUBLIC_KEYFILE         = arena.getInt();
        CURLOPT_SSLCERT                    = arena.getInt();
        CURLOPT_SSLCERTTYPE                = arena.getInt();
        CURLOPT_SSLCERT_BLOB               = arena.getInt();
        CURLOPT_SSLENGINE                  = arena.getInt();
        CURLOPT_SSLENGINE_DEFAULT          = arena.getInt();
        CURLOPT_SSLKEY                     = arena.getInt();
        CURLOPT_SSLKEYTYPE                 = arena.getInt();
        CURLOPT_SSLKEY_BLOB                = arena.getInt();
        CURLOPT_SSLVERSION                 = arena.getInt();
        CURLOPT_SSL_CIPHER_LIST            = arena.getInt();
        CURLOPT_SSL_CTX_DATA               = arena.getInt();
        CURLOPT_SSL_CTX_FUNCTION           = arena.getInt();
        CURLOPT_SSL_EC_CURVES              = arena.getInt();
        CURLOPT_SSL_ENABLE_ALPN            = arena.getInt();
        CURLOPT_SSL_ENABLE_NPN             = arena.getInt();
        CURLOPT_SSL_FALSESTART             = arena.getInt();
        CURLOPT_SSL_OPTIONS                = arena.getInt();
        CURLOPT_SSL_SESSIONID_CACHE        = arena.getInt();
        CURLOPT_SSL_SIGNATURE_ALGORITHMS   = arena.getInt();
        CURLOPT_SSL_VERIFYHOST             = arena.getInt();
        CURLOPT_SSL_VERIFYPEER             = arena.getInt();
        CURLOPT_SSL_VERIFYSTATUS           = arena.getInt();
        CURLOPT_STDERR                     = arena.getInt();
        CURLOPT_STREAM_DEPENDS             = arena.getInt();
        CURLOPT_STREAM_DEPENDS_E           = arena.getInt();
        CURLOPT_STREAM_WEIGHT              = arena.getInt();
        CURLOPT_SUPPRESS_CONNECT_HEADERS   = arena.getInt();
        CURLOPT_TCP_FASTOPEN               = arena.getInt();
        CURLOPT_TCP_KEEPALIVE              = arena.getInt();
        CURLOPT_TCP_KEEPCNT                = arena.getInt();
        CURLOPT_TCP_KEEPIDLE               = arena.getInt();
        CURLOPT_TCP_KEEPINTVL              = arena.getInt();
        CURLOPT_TCP_NODELAY                = arena.getInt();
        CURLOPT_TELNETOPTIONS              = arena.getInt();
        CURLOPT_TFTP_BLKSIZE               = arena.getInt();
        CURLOPT_TFTP_NO_OPTIONS            = arena.getInt();
        CURLOPT_TIMECONDITION              = arena.getInt();
        CURLOPT_TIMEOUT                    = arena.getInt();
        CURLOPT_TIMEOUT_MS                 = arena.getInt();
        CURLOPT_TIMEVALUE                  = arena.getInt();
        CURLOPT_TIMEVALUE_LARGE            = arena.getInt();
        CURLOPT_TLS13_CIPHERS              = arena.getInt();
        CURLOPT_TLSAUTH_PASSWORD           = arena.getInt();
        CURLOPT_TLSAUTH_TYPE               = arena.getInt();
        CURLOPT_TLSAUTH_USERNAME           = arena.getInt();
        CURLOPT_TRAILERDATA                = arena.getInt();
        CURLOPT_TRAILERFUNCTION            = arena.getInt();
        CURLOPT_TRANSFERTEXT               = arena.getInt();
        CURLOPT_TRANSFER_ENCODING          = arena.getInt();
        CURLOPT_UNIX_SOCKET_PATH           = arena.getInt();
        CURLOPT_UNRESTRICTED_AUTH          = arena.getInt();
        CURLOPT_UPKEEP_INTERVAL_MS         = arena.getInt();
        CURLOPT_UPLOAD                     = arena.getInt();
        CURLOPT_UPLOAD_BUFFERSIZE          = arena.getInt();
        CURLOPT_UPLOAD_FLAGS               = arena.getInt();
        CURLOPT_URL                        = arena.getInt();
        CURLOPT_USERAGENT                  = arena.getInt();
        CURLOPT_USERNAME                   = arena.getInt();
        CURLOPT_USERPWD                    = arena.getInt();
        CURLOPT_USE_SSL                    = arena.getInt();
        CURLOPT_VERBOSE                    = arena.getInt();
        CURLOPT_WILDCARDMATCH              = arena.getInt();
        CURLOPT_WRITEDATA                  = arena.getInt();
        CURLOPT_WRITEFUNCTION              = arena.getInt();
        CURLOPT_WS_OPTIONS                 = arena.getInt();
        CURLOPT_XFERINFODATA               = arena.getInt();
        CURLOPT_XFERINFOFUNCTION           = arena.getInt();
        CURLOPT_XOAUTH2_BEARER             = arena.getInt();



    }
}
