/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_CurlEasy */

#ifndef _Included_org_example_CurlEasy
#define _Included_org_example_CurlEasy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_CurlEasy
 * Method:    curl_easy_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_curl_1easy_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_example_CurlEasy
 * Method:    curl_easy_cleanup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_curl_1easy_1cleanup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    perform
 * Signature: (JLorg/example/Request;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_perform
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
