/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Accumulator */

#ifndef _Included_org_example_Accumulator
#define _Included_org_example_Accumulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Accumulator
 * Method:    _allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Accumulator__1allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_Accumulator
 * Method:    _free
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Accumulator__1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
