/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_WriteCallback */

#ifndef _Included_org_example_WriteCallback
#define _Included_org_example_WriteCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_WriteCallback
 * Method:    _allocate
 * Signature: (Lorg/example/IWriteHandler;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_WriteCallback__1allocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_example_WriteCallback
 * Method:    _free
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_WriteCallback__1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
