/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_FILE */

#ifndef _Included_org_example_FILE
#define _Included_org_example_FILE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_FILE
 * Method:    _fopen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_FILE__1fopen
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_example_FILE
 * Method:    _fclose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_FILE__1fclose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
