/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Native */

#ifndef _Included_org_example_Native
#define _Included_org_example_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Native
 * Method:    _get_null
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_Native__1get_1null
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
