/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Arena */

#ifndef _Included_org_example_Arena
#define _Included_org_example_Arena
#ifdef __cplusplus
extern "C" {
#endif
#undef org_example_Arena_TERM
#define org_example_Arena_TERM 0L
/*
 * Class:     org_example_Arena
 * Method:    _init_byte_buffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_example_Arena__1init_1byte_1buffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
