/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_CurlEasy */

#ifndef _Included_org_example_CurlEasy
#define _Included_org_example_CurlEasy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_CurlEasy
 * Method:    curl_easy_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_curl_1easy_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_example_CurlEasy
 * Method:    curl_easy_cleanup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_curl_1easy_1cleanup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    curl_easy_perform
 * Signature: (JLorg/example/Request;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy_curl_1easy_1perform
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_example_CurlEasy
 * Method:    _get_CURL_ERROR_SIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_CurlEasy__1get_1CURL_1ERROR_1SIZE
  (JNIEnv *, jclass);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_url
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1url
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_method
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1method
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _perform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1perform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_error_buffer
 * Signature: (JLjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1error_1buffer
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_example_CurlEasy
 * Method:    _curl_easy_reset
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1curl_1easy_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _curl_easy_strerror
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_CurlEasy__1curl_1easy_1strerror
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _curl_set_headers
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1curl_1set_1headers
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_write_file
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1write_1file
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_write_stream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1write_1stream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_write_callback
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1write_1callback
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_accumulator
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1accumulator
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_post_fields_bytes
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1post_1fields_1bytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_example_CurlEasy
 * Method:    _set_verbose
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_CurlEasy__1set_1verbose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
