/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ReadStream */

#ifndef _Included_org_example_ReadStream
#define _Included_org_example_ReadStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ReadStream
 * Method:    _allocate
 * Signature: (Ljava/io/InputStream;)J
 */
JNIEXPORT jlong JNICALL Java_org_example_ReadStream__1allocate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_example_ReadStream
 * Method:    _free
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_ReadStream__1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
