/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Response */

#ifndef _Included_org_example_Response
#define _Included_org_example_Response
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Response
 * Method:    from_curl
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Response_from_1curl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
