/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Headers */

#ifndef _Included_org_example_Headers
#define _Included_org_example_Headers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Headers
 * Method:    _allocate
 * Signature: ([Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Headers__1allocate
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     org_example_Headers
 * Method:    _free
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_example_Headers__1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
